# Generated by Django 5.2.11 on 2026-03-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('ativa', models.BooleanField(default=True)),
                ('resposta_esperada', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Sim', max_length=3)),
                ('motivo_inaptidao', models.CharField(default='Não especificado', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validade', models.BooleanField(default=True)),
                ('data_hora_submissao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_texto', models.TextField()),
            ],
        ),
    ]
