# Generated by Django 5.2.11 on 2026-02-24 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doadores', '0001_initial'),
        ('triagem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario',
            name='doador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionarios', to='doadores.doador'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='triagem.pergunta'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='questionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='triagem.questionario'),
        ),
    ]
