# Generated by Django 5.2.11 on 2026-02-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='motivo_inaptidao',
            field=models.CharField(default='Não especificado', max_length=255),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='resposta_esperada',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Sim', max_length=3),
        ),
    ]
