# Generated by Django 5.2.11 on 2026-02-20 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processos_doacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dados_Clinicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('hemoglobina', models.FloatField(blank=True, null=True)),
                ('pressao_arterial', models.CharField(blank=True, max_length=10, null=True)),
                ('status_clinico', models.PositiveSmallIntegerField(choices=[(0, 'Inapto'), (1, 'Apto')], default=0)),
                ('processo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_clinicos', to='processos_doacao.processo_doacao')),
            ],
        ),
    ]
