# Generated by Django 5.2.11 on 2026-02-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados_Clinicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('hemoglobina', models.FloatField(blank=True, null=True)),
                ('pressao_arterial', models.CharField(blank=True, max_length=10, null=True)),
                ('status_clinico', models.PositiveSmallIntegerField(choices=[(0, 'Inapto'), (1, 'Apto')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EnfermeiroDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('PRE_TRIAGEM', 'Responsável pela Pré-Triagem'), ('TRIAGEM', 'Responsável pela Triagem'), ('COLETA', 'Responsável pela Coleta')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MedicoDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('PRE_TRIAGEM', 'Responsável pela Pré-Triagem'), ('TRIAGEM', 'Responsável pela Triagem'), ('COLETA', 'Responsável pela Coleta')], max_length=20)),
            ],
        ),
    ]
