# Generated by Django 5.2.11 on 2026-02-20 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_clinicos', '0001_initial'),
        ('enfermeiros', '0001_initial'),
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnfermeiroDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('PRE_TRIAGEM', 'Responsável pela Pré-Triagem'), ('TRIAGEM', 'Responsável pela Triagem'), ('COLETA', 'Responsável pela Coleta')], max_length=20)),
                ('dados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfermeiros_envolvidos', to='dados_clinicos.dados_clinicos')),
                ('enfermeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos_enfermeiros', to='enfermeiros.enfermeiro')),
            ],
        ),
        migrations.CreateModel(
            name='MedicoDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('PRE_TRIAGEM', 'Responsável pela Pré-Triagem'), ('TRIAGEM', 'Responsável pela Triagem'), ('COLETA', 'Responsável pela Coleta')], max_length=20)),
                ('dados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicos_envolvidos', to='dados_clinicos.dados_clinicos')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos_medicos', to='medicos.medico')),
            ],
        ),
    ]
