# Generated by Django 5.2.11 on 2026-02-24 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dados_clinicos', '0001_initial'),
        ('processos_doacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados_clinicos',
            name='processo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_clinicos', to='processos_doacao.processo_doacao'),
        ),
        migrations.AddField(
            model_name='enfermeirodados',
            name='dados',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfermeiros_envolvidos', to='dados_clinicos.dados_clinicos'),
        ),
    ]
