# Generated by Django 5.2.11 on 2026-02-24 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dados_clinicos', '0002_initial'),
        ('enfermeiros', '0001_initial'),
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfermeirodados',
            name='enfermeiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos_enfermeiros', to='enfermeiros.enfermeiro'),
        ),
        migrations.AddField(
            model_name='medicodados',
            name='dados',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicos_envolvidos', to='dados_clinicos.dados_clinicos'),
        ),
        migrations.AddField(
            model_name='medicodados',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos_medicos', to='medicos.medico'),
        ),
    ]
