# Generated by Django 5.2.11 on 2026-02-20 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doadores', '0002_alter_doador_fator_rh_alter_doador_sexo_and_more'),
        ('recepcionistas', '0001_initial'),
        ('triagem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo_Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Recepção'), (2, 'Triagem'), (3, 'Coleta'), (4, 'Concluído'), (0, 'Cancelado')], default=1)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='doadores.doador')),
                ('questionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processo', to='triagem.questionario')),
                ('recepcionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='recepcionistas.recepcionista')),
            ],
        ),
    ]
