# Generated by Django 5.2.11 on 2026-03-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processo_Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Recepção'), (2, 'Pré-Triagem'), (3, 'Triagem'), (4, 'Coleta'), (5, 'Concluído'), (0, 'Cancelado')], default=1)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
