# Generated by Django 5.2.11 on 2026-02-24 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doadores', '0001_initial'),
        ('processos_doacao', '0001_initial'),
        ('recepcionistas', '0001_initial'),
        ('triagem', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo_doacao',
            name='doador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='doadores.doador'),
        ),
        migrations.AddField(
            model_name='processo_doacao',
            name='questionario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processo', to='triagem.questionario'),
        ),
        migrations.AddField(
            model_name='processo_doacao',
            name='recepcionista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='recepcionistas.recepcionista'),
        ),
    ]
