# Generated by Django 5.2.11 on 2026-02-24 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos_doacao', '0001_initial'),
        ('triagem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo_doacao',
            name='questionario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processo', to='triagem.questionario'),
        ),
    ]
