# Generated by Django 5.2.11 on 2026-02-20 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exame_Doador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='exames_doador/%Y/%m/%d/')),
                ('nome_arquivo', models.CharField(blank=True, max_length=100, null=True)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames_doador', to='doadores.doador')),
            ],
        ),
    ]
