# Generated by Django 5.2.11 on 2026-02-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exame_Doador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='exames_doador/%Y/%m/%d/')),
                ('nome_arquivo', models.CharField(blank=True, max_length=100, null=True)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
