# Generated by Django 5.2.11 on 2026-02-24 04:08

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True)),
                ('tipo_sanguineo_declarado', models.CharField(blank=True, choices=[('A', 'Tipo A'), ('B', 'Tipo B'), ('AB', 'Tipo AB'), ('O', 'Tipo O')], max_length=2, null=True)),
                ('fator_rh', models.CharField(blank=True, choices=[('+', 'Positivo (+)'), ('-', 'Negativo (-)')], max_length=1, null=True)),
                ('carteira_doador', models.ImageField(blank=True, null=True, upload_to='carteiras/')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('usuarios.usuario',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
