# Generated by Django 5.2.11 on 2026-02-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doador',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
