# Generated by Django 5.2.11 on 2026-02-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doador',
            name='fator_rh',
            field=models.CharField(blank=True, choices=[('+', 'Positivo (+)'), ('-', 'Negativo (-)')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='doador',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='doador',
            name='tipo_sanguineo_declarado',
            field=models.CharField(blank=True, choices=[('A', 'Tipo A'), ('B', 'Tipo B'), ('AB', 'Tipo AB'), ('O', 'Tipo O')], max_length=2, null=True),
        ),
    ]
