# Generated by Django 5.2.11 on 2026-02-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Sanguineo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('A', 'Tipo A'), ('B', 'Tipo B'), ('AB', 'Tipo AB'), ('O', 'Tipo O')], max_length=2)),
                ('fator_rh', models.CharField(choices=[('+', 'Positivo (+)'), ('-', 'Negativo (-)')], max_length=1)),
            ],
        ),
    ]
