# Generated by Django 5.2.11 on 2026-02-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Aguardando Validação'), (2, 'Validado'), (3, 'Inapto'), (4, 'Utilizado')], default=1)),
                ('data_vencimento', models.DateField()),
                ('validacao_at', models.DateTimeField(blank=True, null=True)),
                ('arquivo_laudo', models.FileField(blank=True, null=True, upload_to='laudos_bolsas/%Y/%m/%d/')),
            ],
        ),
    ]
