# Generated by Django 5.2.11 on 2026-02-20 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('doadores', '0002_alter_doador_fator_rh_alter_doador_sexo_and_more'),
        ('enfermeiros', '0001_initial'),
        ('medicos', '0001_initial'),
        ('processos_doacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Aguardando Validação'), (2, 'Validado'), (3, 'Inapto'), (4, 'Utilizado')], default=1)),
                ('data_vencimento', models.DateField()),
                ('validacao_at', models.DateTimeField(blank=True, null=True)),
                ('arquivo_laudo', models.FileField(blank=True, null=True, upload_to='laudos_bolsas/%Y/%m/%d/')),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolsas_doadas', to='doadores.doador')),
                ('enfermeiro_coleta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bolsas_coletadas', to='enfermeiros.enfermeiro')),
                ('medico_validacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bolsas_validadas', to='medicos.medico')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolsas', to='processos_doacao.processo_doacao')),
                ('tipo_sanguineo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipo_sanguineo')),
            ],
        ),
    ]
