# Generated by Django 5.2.11 on 2026-02-24 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bolsas', '0001_initial'),
        ('core', '0001_initial'),
        ('doadores', '0001_initial'),
        ('enfermeiros', '0001_initial'),
        ('medicos', '0001_initial'),
        ('processos_doacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolsa',
            name='doador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolsas_doadas', to='doadores.doador'),
        ),
        migrations.AddField(
            model_name='bolsa',
            name='enfermeiro_coleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bolsas_coletadas', to='enfermeiros.enfermeiro'),
        ),
        migrations.AddField(
            model_name='bolsa',
            name='medico_validacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bolsas_validadas', to='medicos.medico'),
        ),
        migrations.AddField(
            model_name='bolsa',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolsas', to='processos_doacao.processo_doacao'),
        ),
        migrations.AddField(
            model_name='bolsa',
            name='tipo_sanguineo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipo_sanguineo'),
        ),
    ]
