# Generated by Django 5.2.11 on 2026-03-10 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsas', '0003_auto_bolsas'),
        ('core', '0002_auto_tipos_sanguineos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolsa',
            name='tipo_sanguineo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tipo_sanguineo'),
        ),
    ]
