# Generated by Django 5.2.11 on 2026-03-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsas', '0004_alter_bolsa_tipo_sanguineo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolsa',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
