# Generated by Django 5.2.11 on 2026-03-11 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsas', '0005_alter_bolsa_data_vencimento'),
        ('enfermeiros', '0002_auto_20260301_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolsa',
            name='enfermeiro_coleta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bolsas_coletadas', to='enfermeiros.enfermeiro'),
        ),
    ]
